name: 'UU Create Release Tag'
description: 'Update gradle.properties version and create a release tag'

inputs:
  version:
    description: 'Release version (e.g., 1.0.0). If not specified, uses version from gradle.properties'
    required: false
  gradle_properties_path:
    description: 'Optional folder path where gradle.properties exists. Defaults to root if empty'
    required: false
    default: ''
  release_pat:
    description: 'Github Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.release_pat }}
        fetch-depth: 0  # Fetch all history for tags

    - name: Determine version
      shell: bash
      id: determine-version
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          # Use provided version
          VERSION="${{ inputs.version }}"
          echo "Using provided version: $VERSION"
        else
          # Read version from gradle.properties
          GRADLE_PROPERTIES_DIR="${{ inputs.gradle_properties_path }}"
          # Remove trailing slash if present
          GRADLE_PROPERTIES_DIR="${GRADLE_PROPERTIES_DIR%/}"
          # Construct full path
          if [ -n "$GRADLE_PROPERTIES_DIR" ]; then
            GRADLE_PROPERTIES="${GRADLE_PROPERTIES_DIR}/gradle.properties"
          else
            GRADLE_PROPERTIES="gradle.properties"
          fi
          
          if [ ! -f "$GRADLE_PROPERTIES" ]; then
            echo "::error::gradle.properties file not found at: $GRADLE_PROPERTIES"
            exit 1
          fi
          
          # Extract version line
          VERSION_LINE=$(grep "^version=" "$GRADLE_PROPERTIES" || echo "")
          if [ -z "$VERSION_LINE" ]; then
            echo "::error::No version line found in gradle.properties"
            exit 1
          fi
          
          # Extract version number (format: version=1.2.3)
          VERSION=$(echo "$VERSION_LINE" | sed 's/version=//')
          echo "Using version from gradle.properties: $VERSION"
        fi
        
        # Validate version format
        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::error::Version must be in format x.y.z (e.g., 1.0.0), got: $VERSION"
          exit 1
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Final version: $VERSION"

    - name: Check if tag already exists
      shell: bash
      id: check-tag
      run: |
        VERSION="${{ steps.determine-version.outputs.version }}"
        if git rev-parse "$VERSION" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Error: Tag $VERSION already exists"
          exit 1
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update gradle.properties version
      shell: bash
      run: |
        VERSION="${{ steps.determine-version.outputs.version }}"
        GRADLE_PROPERTIES_DIR="${{ inputs.gradle_properties_path }}"
        # Remove trailing slash if present
        GRADLE_PROPERTIES_DIR="${GRADLE_PROPERTIES_DIR%/}"
        # Construct full path
        if [ -n "$GRADLE_PROPERTIES_DIR" ]; then
          GRADLE_PROPERTIES="${GRADLE_PROPERTIES_DIR}/gradle.properties"
        else
          GRADLE_PROPERTIES="gradle.properties"
        fi
        
        # Update version in gradle.properties
        sed -i "s/^version=.*/version=${VERSION}/" "$GRADLE_PROPERTIES"
        
        # Verify the change
        echo "Updated gradle.properties:"
        grep "^version=" "$GRADLE_PROPERTIES"

    - name: Commit version update
      shell: bash
      id: commit
      run: |
        VERSION="${{ steps.determine-version.outputs.version }}"
        GRADLE_PROPERTIES_DIR="${{ inputs.gradle_properties_path }}"
        # Remove trailing slash if present
        GRADLE_PROPERTIES_DIR="${GRADLE_PROPERTIES_DIR%/}"
        # Construct full path
        if [ -n "$GRADLE_PROPERTIES_DIR" ]; then
          GRADLE_PROPERTIES="${GRADLE_PROPERTIES_DIR}/gradle.properties"
        else
          GRADLE_PROPERTIES="gradle.properties"
        fi
        git add "$GRADLE_PROPERTIES"
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit - version is already $VERSION"
          echo "committed=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Bump version to $VERSION"
          echo "committed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create and push tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.release_pat }}
      run: |
        VERSION="${{ steps.determine-version.outputs.version }}"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git tag -a "$VERSION" -m "Release $VERSION"
        
        # Only push HEAD if there was a commit
        if [ "${{ steps.commit.outputs.committed }}" == "true" ]; then
          git push origin HEAD
        fi
        git push origin "$VERSION"
        
    - name: Summary
      shell: bash
      run: |
        VERSION="${{ steps.determine-version.outputs.version }}"
        echo "✅ Successfully created tag $VERSION"
        echo "📦 The publish workflow will now be triggered automatically"


