name: 'UU Create Release Tag'
description: 'Update gradle.properties version and create a release tag'

inputs:
  version:
    description: 'Release version (e.g., 1.0.0)'
    required: true
  release_pat:
    description: 'Github Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.release_pat }}
        fetch-depth: 0  # Fetch all history for tags

    - name: Validate version format
      shell: bash
      run: |
        if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Version must be in format x.y.z (e.g., 1.0.0)"
          exit 1
        fi

    - name: Check if tag already exists
      shell: bash
      id: check-tag
      run: |
        if git rev-parse "${{ inputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Error: Tag ${{ inputs.version }} already exists"
          exit 1
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update gradle.properties version
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        GRADLE_PROPERTIES="gradle.properties"
        
        # Update version in gradle.properties
        sed -i "s/^version=.*/version=${VERSION}/" "$GRADLE_PROPERTIES"
        
        # Verify the change
        echo "Updated gradle.properties:"
        grep "^version=" "$GRADLE_PROPERTIES"

    - name: Commit version update
      shell: bash
      id: commit
      run: |
        git add gradle.properties
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit - version is already ${{ inputs.version }}"
          echo "committed=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Bump version to ${{ inputs.version }}"
          echo "committed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create and push tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.release_pat }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}"
        
        # Only push HEAD if there was a commit
        if [ "${{ steps.commit.outputs.committed }}" == "true" ]; then
          git push origin HEAD
        fi
        git push origin "${{ inputs.version }}"
        
    - name: Summary
      shell: bash
      run: |
        echo "✅ Successfully created tag ${{ inputs.version }}"
        echo "📦 The publish workflow will now be triggered automatically"


