name: 'UU Publish Prepare'
description: 'Prepare to publish a library'

inputs:
  module_path:
    description: 'Gradle module path'
    required: false
    default: 'library'
  build_number:
    description: 'Build number for versioning'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      shell: bash
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ vars.UU_JAVA_DISTRIBUTION }}
        java-version: ${{ vars.UU_JAVA_VERSION }}
      shell: bash
      
    - name: Update Version
      run: ./scripts/update_version.sh
      env:
        BUILD_NUMBER: ${{ inputs.build_number }}
      shell: bash

    - name: Clean
      run: ./gradlew clean
      shell: bash
    
    - name: Test Library
      run: ./gradlew :${{ inputs.module_path }}:test
      shell: bash
    
    - name: Assemble Library Release
      run: ./gradlew :${{ inputs.module_path }}:assembleRelease
      shell: bash

