name: 'UU Instrumented Tests'
description: 'Run Android instrumented tests'

inputs:
  configuration:
    description: 'Test configuration to run'
    required: false
    default: 'quickGroup'
  module_name:
    description: 'Gradle module name'
    required: false
    default: 'app'
  module_folder:
    description: 'Optional relative path to module source folder.'
    required: false
    default: '.'
  build_suffix:
    description: 'Build Suffix'
    required: false
    default: ''
  java_distribution:
    description: 'Java distribution'
    required: true
  java_version:
    description: 'Java version'
    required: true
  runner:
    description: 'Runner environment'
    required: false
    default: 'ubuntu-latest'

runs:
  using: 'composite'
  steps:
    - name: Prepare Build
      id: prepare
      uses: SilverPineSoftware/UUKotlinBuild/.github/actions/uu-build-prepare@main
      with:
        module_name: ${{ inputs.module_name }}
        module_folder: ${{ inputs.module_folder }}
        build_suffix: ${{ inputs.build_suffix }}
        java_distribution: ${{ inputs.java_distribution }}
        java_version: ${{ inputs.java_version }}
  
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Android System Images
      uses: actions/cache@v4
      id: cache-system-images
      with:
        path: ${{ env.ANDROID_HOME }}/system-images
        key: ${{ inputs.runner }}-android-system-images-v1
        restore-keys: |
          ${{ inputs.runner }}-android-system-images

    - name: Enable KVM for Hardware Acceleration
      if: inputs.runner == 'ubuntu-latest'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Run Instrumented Tests (${{ inputs.configuration }})
      run: |
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew clean \
        :${{ inputs.module_name }}:${{ inputs.configuration }}DebugAndroidTest \
        -Pandroid.testInstrumentationRunnerArguments.notAnnotation=com.silverpine.uu.test.instrumented.annotations.UUInteractionRequired
      shell: bash

    - name: Extract repo name
      id: repo-name
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "name=$REPO_NAME" >> $GITHUB_OUTPUT
      shell: bash
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.repo-name.outputs.name }}-instrumented-test-results-${{ inputs.configuration }}-${{ steps.prepare.outputs.version }}
        path: ${{ inputs.module_folder }}/${{ inputs.module_name }}/build/reports/androidTests

