name: 'UU Tests'
description: 'Run unit tests for a library'

inputs:
  module_name:
    description: 'Gradle module name'
    required: false
    default: 'app'
  module_folder:
    description: 'Optional relative path to module source folder.'
    required: false
    default: '.'
  build_number:
    description: 'Build number for versioning'
    required: true
  java_distribution:
    description: 'Java distribution'
    required: true
  java_version:
    description: 'Java version'
    required: true
  is_snapshot_build:
    description: 'Is snapshot build'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Update Version
      id: update-version
      uses: SilverPineSoftware/UUKotlinBuild/.github/actions/uu-update-version@main
      with:
        module_folder: ${{ inputs.module_folder }}
        build_number: ${{ inputs.build_number }}
        is_snapshot_build: ${{ inputs.is_snapshot_build }}
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
  
    - name: Run Unit Tests
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew clean :${{ inputs.module_name }}:test

      shell: bash
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ steps.update-version.outputs.version }}
        path: ${{ inputs.module_folder }}/${{ inputs.module_name }}/build/reports/tests
        