name: 'UU Build'
description: 'Build a library or application'

inputs:
  module_name:
    description: 'Gradle module name'
    required: false
    default: 'app'
  module_folder:
    description: 'Optional relative path to module source folder.'
    required: false
    default: '.'
  build_suffix:
    description: 'Build Suffix'
    required: false
    default: ''
  java_distribution:
    description: 'Java distribution'
    required: true
  java_version:
    description: 'Java version'
    required: true
  bundle_release:
    description: 'Whether to bundle the release'
    required: false
    default: 'false'
  signing_key:
    description: 'Signing key'
    required: false
    default: ''
  signing_password:
    description: 'Signing password'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Prepare Build
      id: prepare
      uses: SilverPineSoftware/UUKotlinBuild/.github/actions/uu-build-prepare@main
      with:
        module_name: ${{ inputs.module_name }}
        module_folder: ${{ inputs.module_folder }}
        build_suffix: ${{ inputs.build_suffix }}
        java_distribution: ${{ inputs.java_distribution }}
        java_version: ${{ inputs.java_version }}
  
    - name: Clean
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew clean
      shell: bash
    
    - name: Run Unit Tests
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew :${{ inputs.module_name }}:test
      shell: bash

    - name: Setup Signing
      if: inputs.signing_key != ''
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        echo ${{ inputs.signing_key }} | base64 --decode >> release.keystore
      shell: bash
    
    - name: Assemble Release
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew :${{ inputs.module_name }}:assembleRelease
      shell: bash
      env:
        SIGNING_PASSWORD: ${{ inputs.signing_password }}

    - name: Bundle Release
      if: inputs.bundle_release == 'true'
      run: | 
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        ./gradlew :${{ inputs.module_name }}:bundleRelease
      shell: bash
      env:
        SIGNING_PASSWORD: ${{ inputs.signing_password }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ steps.prepare.outputs.version }}
        path: ${{ inputs.module_folder }}/${{ inputs.module_name }}/build/outputs

