name: 'UU Update Version'
description: 'Updates the version in the gradle.properties file'

inputs:
  module_folder:
    description: 'Optional relative path to module source folder.'
    required: false
    default: '.'
  build_suffix:
    description: 'Build Suffix'
    required: false
    default: ''
    
outputs:
  version:
    description: 'The full version string that was set in gradle.properties'

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Read version from gradle.properties
      id: get-version
      run: |
        if [ -n "${{ inputs.module_folder }}" ]; then
          cd "${{ inputs.module_folder }}"
        fi
        VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        BUILD_SUFFIX=${{ inputs.build_suffix }}
        FULL_VERSION=$VERSION
        
        if [ "${{ inputs.build_suffix }}" ]; then
          FULL_VERSION=$VERSION.$BUILD_SUFFIX
          sed -i.bak "s/^version=.*/version=${FULL_VERSION}/" gradle.properties
        fi
        
        echo "version=$FULL_VERSION" >> $GITHUB_OUTPUT
        echo "Full Version: $FULL_VERSION"
        CHECK_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        echo "Check Version: ${CHECK_VERSION}"
      shell: bash
        