name: Publish to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:

  publish:
    name: Publish convention plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ vars.UU_JAVA_DISTRIBUTION }}
          java-version: ${{ vars.UU_JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -Puu_build_version=${{ inputs.version }}
